preparing for CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   # Job for deploy backend
   deploy-backend:
+    if: ${{ secrets.DEPLOY_BACKEND == 'true' }} # Using a flag to control the execution of a job
     runs-on: ubuntu-latest
 
     steps:
@@ -127,12 +128,23 @@ jobs:
         run: |
           eas build -p android --profile production --non-interactive
 
+      - name: Debug APK URL Response
+        working-directory: ./subscription-manager
+        env:
+          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
+        run: |
+          eas build:list --status=finished --limit=1 --json
+
       - name: Get APK URL and Download APK
         working-directory: ./subscription-manager
         env:
           EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
         run: |
-          APK_URL=$(eas build:list --status=finished --limit=1 --json | jq -r '.[0].artifacts.buildUrl')
+          APK_URL=$(eas build:list --status=finished --limit=1 --json | jq -r '.[] | select(.artifacts != null) | .artifacts.buildUrl')
+          if [ -z "$APK_URL" ]; then
+            echo "Error: Unable to find APK URL."
+            exit 1
+          fi
           curl -o app-release.apk "$APK_URL"
 
       - name: Upload APK as artifact
@@ -140,3 +152,10 @@ jobs:
         with:
           name: app-release
           path: ./subscription-manager/app-release.apk
+
+      # - name: Store APK in Google Drive (optional)
+      #   uses: gdrive/drive-upload-action@v1
+      #   with:
+      #     credentials: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
+      #     localFilePath: ./subscription-manager/app-release.apk
+      #     driveFolderName: "APK_Builds"
